name: PyRosetta.notebooks
channels:
  - conda-forge
  - defaults
  - rmg
  - rdkit
dependencies:
  - python=3.7
  - python-blosc=1.7.0
  - biopython=1.74
  - cloudpickle=0.7.0
  - dask=2.11.0
  - dask-jobqueue=0.7.0
  - distributed=2.11.0
  - ipython=7.12.0
  - ipykernel=5.1.4
  - jupyter=1.0.0
  - ipyparallel=6.2.4
  - nb_conda_kernels=2.2.2
  - jupyter_contrib_nbextensions=0.5.1
  - virtualenv=16.7.5
  - matplotlib=3.1.1
  - numpy=1.17.3
  - pandas=0.25.2
  - pip=20.0.2
  - xlrd=1.2.0
  - py3dmol=0.8.0
  - pyrosetta=2020.02
  - python-graphviz=0.13
  - scipy=1.3.1
  - seaborn=0.9.0
